package com.scitalys.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00807E)
val md_theme_light_onPrimary = Color(0xFFE0F0F0)
val md_theme_light_primaryContainer = Color(0xFF80C0BF)
val md_theme_light_onPrimaryContainer = Color(0xFFE0F0F0)
val md_theme_light_secondary = Color(0xFF632DD0)
val md_theme_light_onSecondary = Color(0xFFEEE6F9)
val md_theme_light_secondaryContainer = Color(0xFFB49AE7)
val md_theme_light_onSecondaryContainer = Color(0xFFEEE6F9)
val md_theme_light_tertiary = Color(0xFF00629e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFcee5ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001d34)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfc)
val md_theme_light_onBackground = Color(0xFF191c1c)
val md_theme_light_surface = Color(0xFFfbfdfc)
val md_theme_light_onSurface = Color(0xFF191c1c)
val md_theme_light_surfaceVariant = Color(0xFFdae4e3)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4948)
val md_theme_light_outline = Color(0xFF6f7978)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f0)
val md_theme_light_inverseSurface = Color(0xFF2e3131)

val md_theme_dark_primary = Color(0xFFd3bbff)
val md_theme_dark_onPrimary = Color(0xFF3d0091)
val md_theme_dark_primaryContainer = Color(0xFF5621b0)
val md_theme_dark_onPrimaryContainer = Color(0xFFebdcff)
val md_theme_dark_secondary = Color(0xFF4edad7)
val md_theme_dark_onSecondary = Color(0xFF003736)
val md_theme_dark_secondaryContainer = Color(0xFF00504f)
val md_theme_dark_onSecondaryContainer = Color(0xFF6ff7f3)
val md_theme_dark_tertiary = Color(0xFF96cbff)
val md_theme_dark_onTertiary = Color(0xFF003355)
val md_theme_dark_tertiaryContainer = Color(0xFF004a79)
val md_theme_dark_onTertiaryContainer = Color(0xFFcee5ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1c)
val md_theme_dark_onBackground = Color(0xFFe1e3e2)
val md_theme_dark_surface = Color(0xFF191c1c)
val md_theme_dark_onSurface = Color(0xFFe1e3e2)
val md_theme_dark_surfaceVariant = Color(0xFF3f4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFbec8c7)
val md_theme_dark_outline = Color(0xFF889392)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1c)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e2)

val seed = Color(0xFF00807e)
val error = Color(0xFFba1b1b)